spring:
  profiles:
    active: local

config:
  11st-api:
    url: http://openapi.11st.co.kr/ # openapi/OpenApiService.tmall
    key: db135628136ea74820b2890de13972ea

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/camel
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate # validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200
    open-in-view: false
